# Generated by Django 4.1.7 on 2023-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('moon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('vol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gravity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planet', models.CharField(max_length=20)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('vol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gravity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
