# Generated by Django 4.1.7 on 2023-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetary_play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='moon_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
